version: '3'
 
services:
    reverseproxy:
        image: nginx:alpine
        ports:
            - 80:80
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - proxybroker_net
            - igoods_net

networks:
  igoods_net:
    external:
      name: igoods_default
  proxybroker_net:
    external:
      name: proxybroker_default
